###design.py - сгенерированный графический интерфейс

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMO.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(901, 577)
        self.setFixedSize(901,577)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SimulateBtn = QtWidgets.QPushButton(Dialog)
        self.SimulateBtn.setGeometry(QtCore.QRect(730, 520, 161, 41))
        self.SimulateBtn.setObjectName("SimulateBtn")
        self.PicLabel = QtWidgets.QLabel(Dialog)
        self.PicLabel.setGeometry(QtCore.QRect(290, 0, 601, 141))
        self.PicLabel.setText("")
        self.PicLabel.setPixmap(QtGui.QPixmap("task.jpg"))
        self.PicLabel.setObjectName("PicLabel")
        self.VarLabel = QtWidgets.QLabel(Dialog)
        self.VarLabel.setGeometry(QtCore.QRect(40, 40, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.VarLabel.setFont(font)
        self.VarLabel.setObjectName("VarLabel")
        self.InputBox = QtWidgets.QGroupBox(Dialog)
        self.InputBox.setGeometry(QtCore.QRect(10, 140, 361, 191))
        self.InputBox.setObjectName("InputBox")
        self.TicksLineEdit = QtWidgets.QLineEdit(self.InputBox)
        self.TicksLineEdit.setValidator(QtGui.QIntValidator(1, 999999)) 
        self.TicksLineEdit.setGeometry(QtCore.QRect(160, 150, 113, 25))
        self.TicksLineEdit.setObjectName("TicksLineEdit")
        self.RoLabel = QtWidgets.QLabel(self.InputBox)
        self.RoLabel.setEnabled(True)
        self.RoLabel.setGeometry(QtCore.QRect(10, 30, 41, 19))
        self.RoLabel.setObjectName("RoLabel")
        self.RoLineEdit = QtWidgets.QLineEdit(self.InputBox)
        self.RoLineEdit.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp('^(0(\.\d{1,2}))')))
        self.RoLineEdit.setGeometry(QtCore.QRect(50, 30, 113, 25))
        self.RoLineEdit.setObjectName("RoLineEdit")
        self.P1Label = QtWidgets.QLabel(self.InputBox)
        self.P1Label.setGeometry(QtCore.QRect(10, 70, 41, 19))
        self.P1Label.setObjectName("P1Label")
        self.TiksLabel = QtWidgets.QLabel(self.InputBox)
        self.TiksLabel.setGeometry(QtCore.QRect(10, 150, 151, 21))
        self.TiksLabel.setObjectName("TiksLabel")
        self.P2Label = QtWidgets.QLabel(self.InputBox)
        self.P2Label.setGeometry(QtCore.QRect(10, 110, 41, 19))
        self.P2Label.setObjectName("P2Label")
        self.P1LineEdit = QtWidgets.QLineEdit(self.InputBox)
        self.P1LineEdit.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp('^(0(\.\d{1,2}))')))
        self.P1LineEdit.setGeometry(QtCore.QRect(50, 70, 113, 25))
        self.P1LineEdit.setObjectName("P1LineEdit")
        self.P2LineEdit = QtWidgets.QLineEdit(self.InputBox)
        self.P2LineEdit.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp('^(0(\.\d{1,2}))')))
        self.P2LineEdit.setGeometry(QtCore.QRect(50, 110, 113, 25))
        self.P2LineEdit.setObjectName("P2LineEdit")
        self.StateBox = QtWidgets.QGroupBox(Dialog)
        self.StateBox.setGeometry(QtCore.QRect(10, 340, 361, 221))
        self.StateBox.setObjectName("StateBox")
        self.label000 = QtWidgets.QLabel(self.StateBox)
        self.label000.setGeometry(QtCore.QRect(10, 30, 68, 19))
        self.label000.setObjectName("label000")
        self.label001 = QtWidgets.QLabel(self.StateBox)
        self.label001.setGeometry(QtCore.QRect(10, 60, 68, 19))
        self.label001.setObjectName("label001")
        self.label100 = QtWidgets.QLabel(self.StateBox)
        self.label100.setGeometry(QtCore.QRect(10, 90, 68, 19))
        self.label100.setObjectName("label100")
        self.label101 = QtWidgets.QLabel(self.StateBox)
        self.label101.setGeometry(QtCore.QRect(10, 120, 68, 19))
        self.label101.setObjectName("label101")
        self.label011 = QtWidgets.QLabel(self.StateBox)
        self.label011.setGeometry(QtCore.QRect(10, 150, 68, 19))
        self.label011.setObjectName("label011")
        self.label111 = QtWidgets.QLabel(self.StateBox)
        self.label111.setGeometry(QtCore.QRect(10, 180, 68, 19))
        self.label111.setObjectName("label111")
        self.label000counter = QtWidgets.QLabel(self.StateBox)
        self.label000counter.setGeometry(QtCore.QRect(100, 30, 68, 19))
        self.label000counter.setObjectName("label000counter")
        self.label001counter = QtWidgets.QLabel(self.StateBox)
        self.label001counter.setGeometry(QtCore.QRect(100, 60, 68, 19))
        self.label001counter.setObjectName("label001counter")
        self.label100counter = QtWidgets.QLabel(self.StateBox)
        self.label100counter.setGeometry(QtCore.QRect(100, 90, 68, 19))
        self.label100counter.setObjectName("label100counter")
        self.label101counter = QtWidgets.QLabel(self.StateBox)
        self.label101counter.setGeometry(QtCore.QRect(100, 120, 68, 19))
        self.label101counter.setObjectName("label101counter")
        self.label011counter = QtWidgets.QLabel(self.StateBox)
        self.label011counter.setGeometry(QtCore.QRect(100, 150, 68, 19))
        self.label011counter.setObjectName("label011counter")
        self.label111counter = QtWidgets.QLabel(self.StateBox)
        self.label111counter.setGeometry(QtCore.QRect(100, 180, 68, 19))
        self.label111counter.setObjectName("label111counter")
        self.MetricsBox = QtWidgets.QGroupBox(Dialog)
        self.MetricsBox.setGeometry(QtCore.QRect(400, 140, 491, 221))
        self.MetricsBox.setObjectName("MetricsBox")
        self.ALabel = QtWidgets.QLabel(self.MetricsBox)
        self.ALabel.setEnabled(True)
        self.ALabel.setGeometry(QtCore.QRect(10, 40, 311, 19))
        self.ALabel.setObjectName("ALabel")
        self.LcLabel = QtWidgets.QLabel(self.MetricsBox)
        self.LcLabel.setGeometry(QtCore.QRect(10, 80, 381, 19))
        self.LcLabel.setObjectName("LcLabel")
        self.WcLabel = QtWidgets.QLabel(self.MetricsBox)
        self.WcLabel.setGeometry(QtCore.QRect(10, 130, 371, 19))
        self.WcLabel.setObjectName("WcLabel")
        self.TicksLabel = QtWidgets.QLabel(self.MetricsBox)
        self.TicksLabel.setGeometry(QtCore.QRect(10, 170, 151, 19))
        self.TicksLabel.setObjectName("TicksLabel")
        self.Acounter = QtWidgets.QLabel(self.MetricsBox)
        self.Acounter.setGeometry(QtCore.QRect(330, 40, 68, 19))
        self.Acounter.setObjectName("Acounter")
        self.Lccounter = QtWidgets.QLabel(self.MetricsBox)
        self.Lccounter.setGeometry(QtCore.QRect(400, 80, 61, 20))
        self.Lccounter.setObjectName("Lccounter")
        self.Wccounter = QtWidgets.QLabel(self.MetricsBox)
        self.Wccounter.setGeometry(QtCore.QRect(390, 130, 68, 19))
        self.Wccounter.setObjectName("Wccounter")
        self.Tickscounter = QtWidgets.QLabel(self.MetricsBox)
        self.Tickscounter.setGeometry(QtCore.QRect(170, 170, 68, 19))
        self.Tickscounter.setObjectName("Tickscounter")
        self.DefaultMetricBox = QtWidgets.QGroupBox(Dialog)
        self.DefaultMetricBox.setGeometry(QtCore.QRect(400, 370, 301, 191))
        self.DefaultMetricBox.setObjectName("DefaultMetricBox")
        self.DefAlabel = QtWidgets.QLabel(self.DefaultMetricBox)
        self.DefAlabel.setGeometry(QtCore.QRect(10, 40, 31, 19))
        self.DefAlabel.setObjectName("DefAlabel")
        self.DefLcLabel = QtWidgets.QLabel(self.DefaultMetricBox)
        self.DefLcLabel.setGeometry(QtCore.QRect(10, 90, 31, 19))
        self.DefLcLabel.setObjectName("DefLcLabel")
        self.DefWcLAbel = QtWidgets.QLabel(self.DefaultMetricBox)
        self.DefWcLAbel.setGeometry(QtCore.QRect(10, 150, 51, 19))
        self.DefWcLAbel.setObjectName("DefWcLAbel")
        self.DefALineEdit = QtWidgets.QLineEdit(self.DefaultMetricBox)
        self.DefALineEdit.setEnabled(False)
        self.DefALineEdit.setGeometry(QtCore.QRect(50, 40, 113, 25))
        self.DefALineEdit.setReadOnly(True)
        self.DefALineEdit.setObjectName("DefALineEdit")
        self.DefLcLineEdit = QtWidgets.QLineEdit(self.DefaultMetricBox)
        self.DefLcLineEdit.setEnabled(False)
        self.DefLcLineEdit.setGeometry(QtCore.QRect(50, 90, 113, 25))
        self.DefLcLineEdit.setObjectName("DefLcLineEdit")
        self.DefWcLineEdit = QtWidgets.QLineEdit(self.DefaultMetricBox)
        self.DefWcLineEdit.setEnabled(False)
        self.DefWcLineEdit.setGeometry(QtCore.QRect(50, 150, 113, 25))
        self.DefWcLineEdit.setObjectName("DefWcLineEdit")
        self.InputBox.raise_()
        self.SimulateBtn.raise_()
        self.PicLabel.raise_()
        self.VarLabel.raise_()
        self.StateBox.raise_()
        self.MetricsBox.raise_()
        self.DefaultMetricBox.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Имитационную модель"))
        self.SimulateBtn.setText(_translate("Dialog", "Simulate"))
        self.VarLabel.setText(_translate("Dialog", "ВАРИАНТ 26"))
        self.InputBox.setTitle(_translate("Dialog", "Входные значения"))
        self.TicksLineEdit.setText(_translate("Dialog", "10000"))
        self.RoLabel.setText(_translate("Dialog", "Ro = "))
        self.RoLineEdit.setText(_translate("Dialog", "0.7"))
        self.P1Label.setText(_translate("Dialog", "P1 ="))
        self.TiksLabel.setText(_translate("Dialog", "Количество тактов:"))
        self.P2Label.setText(_translate("Dialog", "P2 = "))
        self.P1LineEdit.setText(_translate("Dialog", "0.7"))
        self.P2LineEdit.setText(_translate("Dialog", "0.75"))
        self.StateBox.setTitle(_translate("Dialog", "Количество переходов в состояние:"))
        self.label000.setText(_translate("Dialog", "000:"))
        self.label001.setText(_translate("Dialog", "001:"))
        self.label100.setText(_translate("Dialog", "100:"))
        self.label101.setText(_translate("Dialog", "101:"))
        self.label011.setText(_translate("Dialog", "011:"))
        self.label111.setText(_translate("Dialog", "111:"))
        self.label000counter.setText(_translate("Dialog", "0"))
        self.label001counter.setText(_translate("Dialog", "0"))
        self.label100counter.setText(_translate("Dialog", "0"))
        self.label101counter.setText(_translate("Dialog", "0"))
        self.label011counter.setText(_translate("Dialog", "0"))
        self.label111counter.setText(_translate("Dialog", "0"))
        self.MetricsBox.setTitle(_translate("Dialog", "Метрики СМО:"))
        self.ALabel.setText(_translate("Dialog", "Абсолютная пропускная способность(A):"))
        self.LcLabel.setText(_translate("Dialog", "Среднее число заявок, находящихся в системе(Lc):"))
        self.WcLabel.setText(_translate("Dialog", "Среднее время пребывания заявки в системе(Wc):"))
        self.TicksLabel.setText(_translate("Dialog", "Количество тактов:"))
        self.Acounter.setText(_translate("Dialog", "0"))
        self.Lccounter.setText(_translate("Dialog", "0"))
        self.Wccounter.setText(_translate("Dialog", "0"))
        self.Tickscounter.setText(_translate("Dialog", "0"))
        self.DefaultMetricBox.setTitle(_translate("Dialog", "Метрики СМО(теоретические):"))
        self.DefAlabel.setText(_translate("Dialog", "A = "))
        self.DefLcLabel.setText(_translate("Dialog", "Lc ="))
        self.DefWcLAbel.setText(_translate("Dialog", "Wc = "))
        self.DefALineEdit.setText(_translate("Dialog", "0.153"))
        self.DefLcLineEdit.setText(_translate("Dialog", "1.419"))
        self.DefWcLineEdit.setText(_translate("Dialog", "8.754"))

